// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MigrationHelper.Db;

#nullable disable

namespace MigrationHelper.Migrations
{
    [DbContext(typeof(MigHelperCtx))]
    partial class MigHelperCtxModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("MigrationHelper.Models.PayPeriod", b =>
                {
                    b.Property<int>("PayPeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Close")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CutOff")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gcc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lcc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Open")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PayDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PayPeriodId");

                    b.ToTable("PayPeriods");
                });

            modelBuilder.Entity("MigrationHelper.Models.PayPeriodGcc", b =>
                {
                    b.Property<int>("PayPeriodGccId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Close")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CutOff")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gcc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Open")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PayDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PayPeriodGccId");

                    b.ToTable("PayPeriodGccs");
                });
#pragma warning restore 612, 618
        }
    }
}
